### PR TITLE
Rename `bazel_features.bzlmod` to `bazel_features.external_deps`

### PR DESCRIPTION
**Pull request by Wyverald**
Continuing the trend of de-emphasizing the name "Bzlmod". I think it would make more sense to group features related to external dependencies together, instead of just Bzlmod features. Not sure whether this should be called `external` or `external_deps` or just `repos`, so I just went with the shortest one.

### CODE REVIEW

**Comment by meteorcloudy** [comment]
I slightly prefer `external_deps` a bit since it's more intuitive.

**Comment by meteorcloudy** [comment]
@alexeagle Can you add @fmeum as a collaborator on this repo? It seems I cannot assign him as reviewer.

**Review by fmeum — APPROVED** [review]

**Comment by fmeum** [comment]
I am in the rules_authors team now, but don't seem to have permissions for this particular repo.

**Review by meteorcloudy — APPROVED** [review]

**Comment by Wyverald** [comment]
@fmeum would you prefer `external_deps` as well? I'm personally undecided so will go with the majority vote.

**Comment by fmeum** [comment]
I also prefer `external_dep` as module extensions naturally fall under it, but aren't repositories.

**Comment by alexeagle** [comment]
@fmeum what access would you like that you don't get as a rules-authors team member?

**Review by fmeum — APPROVED** [review]

**Comment by fmeum** [comment]
> @fmeum what access would you like that you don't get as a rules-authors team member?

Given that we probably want to protect the main branch with required reviews, could you give me write permissions so that I can approve PRs?

**Pull request merged**
