### PR TITLE
Add a feature to test whether Stardoc support module extensions.

### PR DESCRIPTION
**Pull request by phst**
See https://github.com/bazelbuild/stardoc/issues/192.

See logic in
https://github.com/phst/rules_elisp/blob/8606695e977b876ffb38f881f54e50de1606a733/docs/BUILD for prior art.

### CODE REVIEW

**Review by fmeum — COMMENTED** [review]
Could you elaborate on the use case for this? Since stardoc targets are typically built in the module in which they are defined and the support also depends on the stardoc version, I'm not sure whether a feature is the best way to support it.

**Comment by phst** [comment]
In https://github.com/phst/rules_elisp/blob/8606695e977b876ffb38f881f54e50de1606a733/docs/BUILD I selectively build the `extensions` target (for a Starlark file containing module extensions) depending on whether the current Bazel version is 7 or not. Whether this works or not appears to depend mainly on the Bazel version, at least for recent enough Stardoc versions. Happy to switch to a better approach if there's one!

**Comment by fmeum** [comment]
There is, you can detect the required Bazel feature directly: https://github.com/bazelbuild/stardoc/blob/bf441c86274770ea281d21e22292ecdaa6451eaa/stardoc/stardoc.bzl#L88

Let me know if that doesn't work and we can reconsider this.

**Comment by phst** [comment]
It works, thanks!
https://github.com/phst/rules_elisp/commit/57787964fda190305fc7353e618da089ed3aff4b

**Pull request closed without merging**
