### PR TITLE
Add `bazel_features.bzlmod.is_enabled`

### PR DESCRIPTION
**Pull request by fmeum**

### CODE REVIEW

**Comment by fmeum** [comment]
This is mostly me exploring the design space of this repo - this could be a useful addition if we think it's the right place for it.

**Comment by Wyverald** [comment]
I'm a bit undecided. Not entirely sure we want this sort of "flag detection" stuff. Any pros and cons in mind?

**Comment by brentleyjones** [comment]
Pros:
- People ask for this a lot
- There isn't a global attribute to look at to see if it's enabled
- That's what this features repo is about, right?

Cons:
- I can't really think of any? If people need this (and there are numerous examples of the need), why not add it?

**Comment by Wyverald** [comment]
I'm sufficiently convinced -- tried thinking of substantial cons, couldn't think of any.

**Review by Wyverald — APPROVED** [review]

**Pull request merged**
