### PR TITLE
feat: add treeartifact_permits_uplevel symlinks feature

### PR DESCRIPTION
**Pull request by thesayyn**
A feature gate for https://github.com/bazelbuild/bazel/pull/21263

### CODE REVIEW

**Comment by meteorcloudy** [comment]
Let's wait a bit until https://github.com/bazelbuild/bazel/pull/21263 is actually in 7.1.

**Review by meteorcloudy — APPROVED** [review]

**Comment by thesayyn** [comment]
I don't know the release cadence for this repo. When can i expect a new release? (just for my curiosity)

**Comment by fmeum** [comment]
@thesayyn I pushed a new release: https://github.com/bazelbuild/bazel-central-registry/pull/1518

**Comment by thesayyn** [comment]
Thank you @fmeum!

**Pull request merged**
